import type { Metadata } from 'next';
import './globals.css';
import { spaceGrotesk } from '@/utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={spaceGrotesk.className} lang='en'>
      <body>{children}</body>
    </html>
  );
}
